email_validate: 50
email: "tieuhodo96@gmail.@gmail.com"
reset_password: 6
confirm: 6
wait_time: 10
image:
  size: 150
page: 5
devise_friendly_token_min: 0
devise_friendly_token_max: 20
image_post:
  width: 150
  height: 277
image_post:
  size: 250 x 250
  post_size: 150 x 150
rows: 2
comment:
  content:
    maxlength: 200
post:
  picture_size: 5
  title:
    maxlength: 20
  content:
    maxlength: 500
  post_type: "Post"
